$STITLE Input file: VARINIT.INC. Initialization of variables. Standard CGE modeling system, Version 1.01

  CPI.L           = CPI0;
  DMPS.L          = DMPS0;
  DPI.L           = DPI0;
  DTINS.L         = DTINS0;
  EG.L            = EG0;
  EH.L(H)         = EH0(H);
  EXR.L           = EXR0;
  FSAV.L          = FSAV0;
  GADJ.L          = GADJ0;
  GOVSHR.L        = GOVSHR0;
  GSAV.L          = GSAV0;
  IADJ.L          = IADJ0;
  INVSHR.L        = INVSHR0;
  MPS.L(INSDNG)   = MPS0(INSDNG);
  MPSADJ.L        = MPSADJ0;
  PA.L(A)         = PA0(A);
  PDD.L(C)        = PDD0(C);
  PDS.L(C)        = PDS0(C);
  PINTA.L(A)      = PINTA20(A) ;
  PE.L(C)         = PE0(C);
  PM.L(C)         = PM0(C);
  PQ.L(C)         = PQ0(C);

  PVAE.L(A)       = PVAE0(A);
  PENE.L(A)       = PENE0(A);
  PVA.L(A)        = PVA0(A);

  PWE.L(C)        = PWE0(C);
  PWM.L(C)        = PWM0(C);
  PX.L(C)         = PX0(C);
  PXAC.L(A,C)     = PXAC0(A,C);
  QA.L(A)         = QA0(A);
  QD.L(C)         = QD0(C);
  QE.L(C)         = QE0(C);
  QF.L(F,A)       = QF0(F,A);
  QFS.L(F)        = QFS0(F);
  QG.L(C)         = QG0(C);
  QH.L(C,H)       = QH0(C,H);
  QHA.L(A,C,H)    = QHA0(A,C,H);
  QINT.L(C,A)     = QINT0(C,A);

  QINTA.L(A)      = QINTA20(A) ;

  QINV.L(C)       = QINV0(C);
  QINVTOT.L       = QINVTOT0     ;
  KSTOCKP.L       = KSTOCKP0      ;
  KSTOCK.L        = KSTOCK0      ;
  CAPG.L          = CAPG0  ;
  QM.L(C)         = QM0(C);
  QQ.L(C)         = QQ0(C);
  QT.L(C)         = QT0(C);
  QVA.L(A)        = QVA0(A);
  QVAE.L(A)       = QVAE0(A) ;
  QENE.L(A)       = QENE0(A) ;
  QX.L(C)         = QX0(C);
  QXAC.L(A,C)     = QXAC0(A,C);
  TABS.L          = TABS0;
  TRII.L(INSDNG,INSDNGP) = TRII0(INSDNG,INSDNGP);
  TINS.L(INSDNG)  = TINS0(INSDNG);
  TINSADJ.L       = TINSADJ0;
  WALRAS.L        = WALRAS0;
  WALRASSQR.L     = 0 ;
  WF.L(F)         = WF0(F);
  WFDIST.L(F,A)   = WFDIST0(F,A);
  YF.L(f)         = YF0(f);
  YG.L            = YG0;
  YI.L(INS)       = YI0(INS);
  YIF.L(INS,F)    = YIF0(INS,F);

*#*#*#*#*# THE END OF VARINIT.INC #*#*#*#*
